repos:
  # - repo: https://github.com/astral-sh/ruff-pre-commit
  #   # Ruff version.
  #   rev: v0.0.282
  #   hooks:
  #   - id: ruff
  #     args: [., --fix, --exit-non-zero-on-fix ]
  #     exclude: '(^scripts|^docs)/.*'
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    - id: black
      language_version: python3
      exclude: '(^scripts|^docs)/.*'